language: java

os:
  - linux

addons:
  sonarcloud:
    organization: "dachiarelli89"
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=dachiarelli89_istat-locations

deploy:
  provider: releases
  user: "dachiarelli89"
    password: "${GITHUB_TOKEN}"
  file: target/istat-locations-*
  skip_cleanup: true
  on:
    tags: true