language: java

os:
  - linux

addons:
  sonarcloud:
    organization: "dachiarelli89"
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- sonar-scanner
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=dachiarelli89_istat-locations
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=dachiarelli89_istat-locations