language: java

os:
  - linux

addons:
  sonarcloud:
    organization: "dachiarelli89"
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=dachiarelli89_istat-locations

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true